version: '3.5'

services:

  go-graphql:
    image: golang:latest
    working_dir: /go/src/app
    container_name: go-graphql
    tty: true
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    